global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 5s       # Fast alert grouping for instant notifications
  group_interval: 5s
  repeat_interval: 12h
  receiver: 'telegram'

receivers:
- name: 'telegram'
  telegram_configs:
  - bot_token: '8510238595:AAFQHvMSlAyngO-Rmw3OHPAjfeMAocovYUs'
    chat_id: 566544813
    api_url: 'https://api.telegram.org'
    send_resolved: true
    message: |
      {{ if eq .Status "firing" }}🔴 *ALERTA ACTIVADA* 🔴{{ else }}🟢 *ALERTA RESUELTA* 🟢{{ end }}
      
      *Alerta:* {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}
      *Detalle:* {{ range .Alerts }}{{ .Annotations.description }}{{ end }}
      *Severidad:* `{{ range .Alerts }}{{ .Labels.severity }}{{ end }}`
